name: ci

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  TEST_TAG: user/create-subtraction:test

jobs:
  commitlint:
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build --target base .
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        id: build-push
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
          target: test
      - name: Test
        run: docker run ${{ env.TEST_TAG }}
  release:
    runs-on: ubuntu-24.04
    if: github.event_name == 'push'
    needs: [build, test]
    outputs:
      git-tag: ${{ steps.semantic.outputs.git-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install semantic-release
        run: npm i semantic-release@v24.2.5 @semantic-release/exec@v7.1.0 conventional-changelog-conventionalcommits@9.0.0
      - name: Run semantic-release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  ghcr:
    runs-on: ubuntu-24.04
    needs: [release]
    if: github.repository_owner == 'Virtool'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.release.outputs.git-tag }}
      - name: Write VERSION file
        run: echo ${{ needs.release.outputs.git-tag }} > VERSION
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          context: 'git'
          images: ${{ env.REGISTRY }}/virtool/create-subtraction
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          target: "base"